/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'reorderPoint' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'currentStock' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FrequentCustomer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'orderCount' : IDL.Nat,
  'lastPurchaseMonth' : IDL.Text,
  'totalSpent' : IDL.Float64,
});
export const HighValueCustomer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'orderCount' : IDL.Nat,
  'lastPurchaseMonth' : IDL.Text,
  'totalSpent' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicine' : IDL.Func([Medicine], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFrequentCustomers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FrequentCustomer)],
      ['query'],
    ),
  'getHighValueCustomers' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(HighValueCustomer)],
      ['query'],
    ),
  'getMedicineById' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMedicine' : IDL.Func([Medicine], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'reorderPoint' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'currentStock' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FrequentCustomer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'orderCount' : IDL.Nat,
    'lastPurchaseMonth' : IDL.Text,
    'totalSpent' : IDL.Float64,
  });
  const HighValueCustomer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'orderCount' : IDL.Nat,
    'lastPurchaseMonth' : IDL.Text,
    'totalSpent' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicine' : IDL.Func([Medicine], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFrequentCustomers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FrequentCustomer)],
        ['query'],
      ),
    'getHighValueCustomers' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(HighValueCustomer)],
        ['query'],
      ),
    'getMedicineById' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMedicine' : IDL.Func([Medicine], [], []),
  });
};

export const init = ({ IDL }) => { return []; };