/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FrequentCustomer {
  'id' : string,
  'name' : string,
  'orderCount' : bigint,
  'lastPurchaseMonth' : string,
  'totalSpent' : number,
}
export interface HighValueCustomer {
  'id' : string,
  'name' : string,
  'orderCount' : bigint,
  'lastPurchaseMonth' : string,
  'totalSpent' : number,
}
export interface Medicine {
  'id' : string,
  'reorderPoint' : bigint,
  'name' : string,
  'isActive' : boolean,
  'category' : string,
  'unitPrice' : number,
  'currentStock' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicine' : ActorMethod<[Medicine], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFrequentCustomers' : ActorMethod<[bigint], Array<FrequentCustomer>>,
  'getHighValueCustomers' : ActorMethod<[number], Array<HighValueCustomer>>,
  'getMedicineById' : ActorMethod<[string], Medicine>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMedicine' : ActorMethod<[Medicine], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];